#!/bin/bash
binary=$BINARY decimal=0 counter=0 while [ $binary -ne 0 ] do digit=$((binary % 10)) decimal=$((decimal + digit * 2**counter)) counter=$((counter + 1)) binary=$((binary / 10)) done echo $decimal
